Njavokhir/new world transition #21
globe-and-citizen/gc-web pull request #40
Opened 2024-10-13 19:17 UTC by NJavokhir

#### **Title: Add Smooth Fade-out for Raining Effect**

#### **Summary:**
This PR addresses and closes issue #21 by implementing a smoother fade-out animation for the raining effect and introducing a progress-loading widget during chapter transitions.

#### **Key Changes:**
1. **Smooth Fade-out for Raining Effect:**
   - Updated the `stopRainingEffect`, `startRainingEffect` to smoothly fade out the canvas over 1 second before removing it.
   
   Issue #21 is now resolved with these updates.

2024-10-15 01:12 UTC, stravid87 commented
Good to see progress. There are still some problems here.

2024-10-15 01:22 UTC, stravid87 requested changes
You should open your PRs against, `njavokhir-base-branch`, not develop.
Some progress -- but we're not quite there yet.

2024-10-15 01:22 UTC, stravid87 commented on src/utils/codeRainingEffect.ts
> +  canvas.style.transition = 'opacity 1s ease';
Here you are using CSS styles. However, on line 95 of `src/views/HomeView.vue`, you again are using transitions. Are both necessary? Perhaps one or the other?

2024-10-15 01:22 UTC, stravid87 commented on src/utils/codeRainingEffect.ts
> +  if (canvas) {
From here, Line 28 to Line 59 is your main function that creates the raining code effect. Everything above and below is code you'll write to have it transition appropriately. I notice a lot of timers. Try to architect a more graceful solution that takes advantage of asynchronous calls, callbacks, or other mechanisms to make the transitions between chapters smooth and predictable.

2024-10-15 01:22 UTC, stravid87 commented on src/utils/codeRainingEffect.ts
> +    canvas.style.opacity = '0';
I am not seeing a slow fade out.

2024-10-15 01:22 UTC, stravid87 commented on src/utils/codeRainingEffect.ts
> +    }, 1000);
This causes the effect to disappear abruptly. It should fade out.

2024-10-15 01:22 UTC, stravid87 commented on src/views/HomeView.vue
> +<style lang="scss">
Are we using Scss? Copy/paste is okay if it get cleaned up. I feel like this has been left behind.

2024-10-16 16:07 UTC, NJavokhir commented
I looked your feedbacks and do some changes related to them. I am going to close this PR because I opened it for `develop` branch. New PR has already opened for `njavokhir-base-branch` which is #41 .

2024-10-16 16:07 UTC, closed without merging